// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RalfyGenao_Ap1_P1.DAL;

#nullable disable

namespace RalfyGenao_Ap1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241012020040_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("RalfyGenao_Ap1_P1.Models.CobroDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CobroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorCobrado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DetalleId");

                    b.HasIndex("CobroId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("CobroDetalle");
                });

            modelBuilder.Entity("RalfyGenao_Ap1_P1.Models.Cobros", b =>
                {
                    b.Property<int>("CobroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.HasKey("CobroId");

                    b.HasIndex("DeudorId");

                    b.ToTable("Cobros");
                });

            modelBuilder.Entity("RalfyGenao_Ap1_P1.Models.Deudor", b =>
                {
                    b.Property<int>("DeudorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrestamoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeudorId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("Deudor");

                    b.HasData(
                        new
                        {
                            DeudorId = 1,
                            Nombres = "Ralfy"
                        },
                        new
                        {
                            DeudorId = 2,
                            Nombres = "Elian"
                        },
                        new
                        {
                            DeudorId = 3,
                            Nombres = "Albert"
                        },
                        new
                        {
                            DeudorId = 4,
                            Nombres = "Reylin"
                        },
                        new
                        {
                            DeudorId = 5,
                            Nombres = "Alfa"
                        });
                });

            modelBuilder.Entity("RalfyGenao_Ap1_P1.Models.Prestamos", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Balance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Monto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PrestamoId");

                    b.HasIndex("DeudorId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("RalfyGenao_Ap1_P1.Models.CobroDetalle", b =>
                {
                    b.HasOne("RalfyGenao_Ap1_P1.Models.Cobros", "cobros")
                        .WithMany("CobroDetalles")
                        .HasForeignKey("CobroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RalfyGenao_Ap1_P1.Models.Prestamos", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");

                    b.Navigation("cobros");
                });

            modelBuilder.Entity("RalfyGenao_Ap1_P1.Models.Cobros", b =>
                {
                    b.HasOne("RalfyGenao_Ap1_P1.Models.Deudor", "Deudor")
                        .WithMany()
                        .HasForeignKey("DeudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deudor");
                });

            modelBuilder.Entity("RalfyGenao_Ap1_P1.Models.Deudor", b =>
                {
                    b.HasOne("RalfyGenao_Ap1_P1.Models.Prestamos", null)
                        .WithMany("Deudores")
                        .HasForeignKey("PrestamoId");
                });

            modelBuilder.Entity("RalfyGenao_Ap1_P1.Models.Prestamos", b =>
                {
                    b.HasOne("RalfyGenao_Ap1_P1.Models.Deudor", "Deudor")
                        .WithMany()
                        .HasForeignKey("DeudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deudor");
                });

            modelBuilder.Entity("RalfyGenao_Ap1_P1.Models.Cobros", b =>
                {
                    b.Navigation("CobroDetalles");
                });

            modelBuilder.Entity("RalfyGenao_Ap1_P1.Models.Prestamos", b =>
                {
                    b.Navigation("Deudores");
                });
#pragma warning restore 612, 618
        }
    }
}
